default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("PGHOST", "127.0.0.1") %>
  port: <%= ENV.fetch("PGPORT", 5432) %>
  username: <%= ENV.fetch("PGUSER", ENV["USER"]) %>
  password: <%= ENV["PGPASSWORD"] %>

development:
  <<: *default
  database: salary_management_tdd_development

test:
  <<: *default
  database: <%= ENV.fetch("TEST_DATABASE", "salary_management_tdd_test") %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
